### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by arita37** [aredier/trelawney#116]
Thanks for the work, this is a good step forward.
To make easier integration of new interpretation framework,
Can you detail in docs    :   
      API to include new Interpretation models.
        
For API, building you can refer to this framework   :  
      https://github.com/arita37/mlmodels

**Comment by aredier** [comment]
Hello, I will add a section in the Contributing part of doc indeed.
In the mean time, to use the common interface, you need to subclasss the [`BaseExplainer` class](https://trelawney.readthedocs.io/en/latest/trelawney.html#trelawney.base_explainer.BaseExplainer):

as you can read in that part of the doc:
>will need to define some behaviors when implementing your new explainer. In order to do so, override:
>
> - the fit method that defines how (if needed) the explainer should be fited
> - the feature_importance method that extracts the relative importance of each feature on a dataset globally
> - the explain_local method that extracts the relative impact of each feature on the final decisionfor every sample in a dataset

**Comment by arita37** [comment]
Please a template with pre-defined class/methods.

Just easier.

**Comment by aredier** [comment]
#117 should solve this (you can find the methods to override there). If you need a usage example, you can check existing interpreters.

**Comment by aredier** [comment]
closing this since the branch is merged
